name: Cl

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Set Password
      run: |
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Set Wallpaper
      run: |
        Invoke-WebRequest "https://i.ytimg.com/vi/8YodvN2DKoY/hq720.jpg?sqp=-oaymwE7CK4FEIIDSFryq4qpAy0IARUAAAAAGAElAADIQj0AgKJD8AEB-AH-CYAC0AWKAgwIABABGGAgZShOMA8=&rs=AOn4CLAm0NNnXcLl-Tf9Dy1t9NHLHBcrgA" -OutFile "$env:TEMP\wallpaper.jpg"

        reg add "HKCU\Control Panel\Desktop" /v Wallpaper /t REG_SZ /d "$env:TEMP\wallpaper.jpg" /f

        RUNDLL32.EXE user32.dll,UpdatePerUserSystemParameters

    - name: Set User Icon
      run: |
        Invoke-WebRequest "https://media.discordapp.net/attachments/1499655960187244575/1502254363492614255/image.png?ex=69ff0ae6&is=69fdb966&hm=8583390eac5ec7ba5a20b371ff9f83667e5c85715400ea67e725493d6c5e24ec&=&format=webp&quality=lossless&width=366&height=364" -OutFile "C:\ProgramData\Microsoft\User Account Pictures\user.png"

    - name: Install Tailscale
      run: |
        Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi -OutFile tailscale.msi
        Start-Process msiexec.exe -ArgumentList "/i tailscale.msi /quiet /norestart" -Wait

    - name: Connect Tailscale
      run: |
        & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TS_AUTHKEY }}

    - name: Show Tailscale IP
      run: |
        & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4

    - name: Keep Alive
      run: |
        while ($true) {
          Start-Sleep -Seconds 300
        }
