name: Cl

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Set Password
      run: |
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Set Wallpaper
      run: |
        Invoke-WebRequest "https://wallpapers.com/images/hd/cool-windows-desktop-jq4k3xobagisqza4.jpg"

        reg add "HKCU\Control Panel\Desktop" /v Wallpaper /t REG_SZ /d "$env:TEMP\wallpaper.jpg" /f

        RUNDLL32.EXE user32.dll,UpdatePerUserSystemParameters

    - name: Set User Icon
      run: |
        Invoke-WebRequest "https://art.ngfiles.com/images/2947000/2947208_op4teen_new-pfp-insta.jpg?f1672054720" -OutFile "C:\ProgramData\Microsoft\User Account Pictures\user.png"

    - name: Install Tailscale
      run: |
        Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi -OutFile tailscale.msi
        Start-Process msiexec.exe -ArgumentList "/i tailscale.msi /quiet /norestart" -Wait

    - name: Connect Tailscale
      run: |
        & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TS_AUTHKEY }}

    - name: Show Tailscale IP
      run: |
        & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4

    - name: Keep Alive
      run: |
        while ($true) {
          Start-Sleep -Seconds 300
        }
